server.port=8087

spring.application.name=springmsproj10-customerservice

spring.datasource.url=jdbc:oracle:thin:@localhost:1521:orcl
spring.datasource.username=MYDBMAIN
spring.datasource.password=CHIRAG
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
